- FK (부모의 의존하는 데이터이거나,
        널값을 허용

DROP TABLE TEST_FK;

CREATE TABLE TEST_FK(
        ID      CHAR(3) PRIMARY KEY ,
        NAME    VARCHAR(50) NOT NULL,
        LID     CHAR(2) ,
        FOREIGN KEY(LID) REFERENCES LOCATION(LOCATION_ID)        
)

INSERT INTO TEST_FK VALUES('X','JSLIM','OT')

SELECT  *
FROM    LOCATION ;

SELECT  *
FROM    TEST_FK


CREATE TABLE TEST_COMPOSIT_PK(  
    ID      VARCHAR2(50),
    NAME    VARCHAR2(50),
    SALARY  NUMBER      CHECK (SALARY > 0)  ,     -- (7)을 해주면 넘버의 자릿수 지정 ,2를 하면 2자리는 실수형으로 쓰겠다는 뜻
    GENDER  CHAR(1)     CHECK (GENDER IN ('M' , 'F')) ,  
    PRIMARY KEY(ID, NAME)
)

INSERT INTO TEST_COMPOSIT_PK VALUES('JSLIM','임정섭',100,'M') 

SELECT  *
FROM    TEST_COMPOSIT_PK    


CREATE TABLE TEST_COMPOSIT_FK(
    PID     VARCHAR2(50) PRIMARY KEY,
    ID      VARCHAR2(50),
    NAME    VARCHAR2(50),
    FOREIGN KEY(ID, NAME) REFERENCES TEST_COMPOSIT_PK (ID, NAME)
)

INSERT INTO TEST_COMPOSIT_FK VALUES('P003','JSLIM','임정섭')

SELECT  *
FROM    TEST_COMPOSIT_FK


DROP TABLE TEST_COMPOSIT_FK

CREATE TABLE TEST_S1(
    SID     VARCHAR2(50) PRIMARY KEY,
    PHONE   NUMBER
)

CREATE TABLE TEST_S2(
    TID     VARCHAR2(50) PRIMARY KEY,
    NAME    VARCHAR2(50) DEFAULT 'DEFAULT'
)

CREATE TABLE TEST_CHILD(
    CID     VARCHAR2(50) PRIMARY KEY,
    SID     VARCHAR2(50) REFERENCES TEST_S1(SID) ,
    TID     VARCHAR2(50) REFERENCES TEST_S2(TID)
)

INSERT INTO TEST_S1 VALUES('최호동','01023127619') ;

INSERT INTO TEST_S2 VALUES('임호수233',NULL) ;

INSERT INTO TEST_CHILD VALUES('임호진','최호동','임호수') ;



SELECT  *
FROM    TEST_CHILD


